### ISSUE TITLE
SSH private deploy key found in commit

### ISSUE THREAD

**Issue by oSumAtrIX** [AarizYT/Aariz-Build-Env#1]
Do not commit private keys:  https://github.com/AarizYT/Aariz-Build-Env/blob/37d8fe28445d7cb071fc92e38de82fe4955ffc3b/free_librespot_private_key
Instead, use deploy keys.

**Comment by AarizYT** [comment]
Sorry for the trouble, I can't clone your repository anymore which I am assuming is because of this, I have deleted the private key from the repository so I hope you can fix this problem now, I will use a deploy key for this next time.

**Comment by oSumAtrIX** [comment]
I have reverified the deploy key and it should work again. Generally, I would have to renew it but it is fine in this case.
